### ISSUE TITLE
User eBPF programm Selection

### ISSUE THREAD

**Issue by tamemo99** [amosproj/amos2024ws03-android-zero-instrumentation#41]
# User Story: 
## As a User I want to:
- View a list of all eBPF programms in the backend
- Select a certain Programm to be loaded in from the backend in my UI

## Technical Benefit: 
- Encapsulation of the user space daemon 

## Acceptance criteria:
- Display an error if the ebpf loader is not working, or send user to home screen

## Definition of done (DoD)
- All acceptance criteria were met
- Feature has been fully implemented

**Comment by BenediktZinn** [comment]
Development of backend part of this issue started on branch [feat/backend_daemon](https://github.com/amosproj/amos2024ws03-android-zero-instrumentation/tree/feat/backend_daemon)

**Comment by fhilgers** [comment]
- [ ] Frontend (see #62)
- [ ] Backend (see #61)
- [ ] Proto Files (see #57)
- [ ] Kotlin interface (see #58)
- [ ] Client Sdk (see #60)
- [ ] Testclient (see #59)
